<!-- templates/show.phtml -->

<?php require 'components/header.phtml'; ?>

<!--?php Displays a message that the URL was added or checked successfully ?-->
<?php if (count($flash) > 0) : ?>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <div class="alert alert-<?= $flash['success'] ? 'success' : 'warning' ?> " role="alert"> <?= $message ?> </div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $url['name'] ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $url['id'] ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url['name'] ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $url['created_at'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>

    <h2 class="mt-5 mb-3">Проверки</h2>
    <form method="post" action="/urls/<?= $url['id'] ?>/checks">
        <input type="submit" class="btn btn-primary" value="Запустить проверку">
    </form>
    <table class="table table-bordered table-hover mt-3" data-test="checks">
        <tbody>
            <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
            </tr>
            <!--?php foreach ($checks as $check): ?-->
            <?php foreach ($checks as $check) : ?>
            <tr>
                <td><?= $check['id'] ?></td>
                <td><?= $check['status_code'] ?></td>
                <td class="text-break"><?= $check['h1'] ?></td>
                <td class="text-break"><?= $check['title'] ?></td>
                <td class="text-break"><?= $check['description'] ?></td>
                <td><?= $check['created_at'] ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    </div>
</main>

<?php require 'components/footer.phtml'; ?>