<!-- templates/show.phtml -->

<?php require 'components/header.phtml'; ?>

<!--Displays a message that the URL was added successfully-->
<?php foreach ($messages as $message): ?>
    <div class="alert alert-success" role="alert">
        <?= $message ?>
    </div>
<?php endforeach; ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайт: <?= $url['name'] ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td><?= $url['id'] ?></td>
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= $url['name'] ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= $url['created_at'] ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>

<?php require 'components/footer.phtml'; ?>