<!-- templates/urls.phtml -->

<?php require 'components/header.phtml'; ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Сайты</h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                    <!--?php foreach ($urls as $url): ?-->
                    <?php foreach ($urls as $url) : ?>
                    <tr>
                        <td><?= $url['id'] ?></td>
                        <td><a href="/urls/<?= $url['id'] ?>"><?= $url['name'] ?></a></td>
                        <td><?= $url['last_checks'] ?></td>
                        <td><?= $url['status_code'] ?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</main>

<?php require 'components/footer.phtml'; ?>