<!-- templates/oops.phtml -->

<?php require 'components/header.phtml'; ?>

<main class="flex-grow-1">
    <div class="container-lg mt-3">
        <h1>Упс что-то пошло не так</h1>
        <div class="row row-cols-1 row-cols-lg-2 align-items-lg-center">
            <div class="col">
                <h2 class="h2 mb-4">
                Ошибка 500
                </h2>
            </div>
        </div>
    </div>
</main>

<?php require 'components/footer.phtml'; ?>