name: project-check

on: push

jobs:
  build:
    runs-on: Ubuntu 20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: make install

      - name: Linter
        run: make lint